print("Hello Git")
print("Hello ayush")
b = float(input("Enter Investment Amount :"))
c = float(input("Enter Current  Amount :"))
d = float(input("Enter SGB1 Amount :"))
e = float(input("Enter SGB2 Amount :"))
f = float(input("Enter SGB3 Amount :"))
g = float(input("Enter SGB4 Amount :"))
h = float(input("Enter Bond1 Amount :"))
i = float(input("Enter Bond2 Amount :"))
j = float(input("Enter Bond3 Amount :"))
k = float(input("Enter Bond4 Amount :"))
l = float(input("Enter Nifty Amount :"))
m = float(input("Enter Mutual Fund Amount :"))
n = float(input("Enter NPS Amount :"))

